### ISSUE TITLE
使用CentOS7.6 make devel提示异常

### ISSUE THREAD

**Issue by StatLee** [alibaba/diagnose-tools#55]
原声CentOS7.6，内核版本3.10.0-957.21.3.el7.x86_64，make devel时，应该是缺少依赖

![image](https://user-images.githubusercontent.com/11553945/99208649-07246680-27fc-11eb-8968-177fa61e8a21.png)

**Comment by 0x0916** [comment]
```
       check-update
              Implemented  so  you  could  know if your machine had any updates that needed to be applied without running it interactively.
              Returns exit value of 100 if there are packages available for an update. Also returns a list of the packages to be updated in
              list format. Returns 0 if no packages are available for update. Returns 1 if an error occurred.  Running in verbose mode also
              shows obsoletes.
```
Makefile 中的`yum check-update`返回100应该是正常的。可以将这行代码`yum check-update`先注释掉试试。

**Comment by StatLee** [comment]
> ```
>        check-update
>               Implemented  so  you  could  know if your machine had any updates that needed to be applied without running it interactively.
>               Returns exit value of 100 if there are packages available for an update. Also returns a list of the packages to be updated in
>               list format. Returns 0 if no packages are available for update. Returns 1 if an error occurred.  Running in verbose mode also
>               shows obsoletes.
> ```
> 
> Makefile 中的`yum check-update`返回100应该是正常的。可以将这行代码`yum check-update`先注释掉试试。

谢谢指教，理论来说确实应该把这句关掉，因为不经过评估的update可能会导致生产环境崩掉，不过我是做demo，所以我搞了个脚本跑了1个小时自动把依赖给装齐了……

脚本如下：

#/bin/sh
makers=$(make devel 2>\&1)
makerscode=$(echo $?)
while [ $makerscode -eq 2 ]
do
    makers=$(make devel 2>\&1)
    makerscode=$(echo $?)
    mtmakers=$($makers |tail -n 1)
    yumrpm=$(echo $mtmakers | awk '{print $1}' | tail -n 1)
    yum install -y $yumrpm > /dev/null 2>\&1
    if [ $? -eq 0 ];then
        echo "install $yumrpm successful!" >> /tmp/diagnose-tools-maked.log
        echo "install $yumrpm successful!"
    else
        echo "install $yumrpm rpm error" >> /tmp/diagnose-tools-maked.log
        echo "install $yumrpm rpm error"
    fi
done
echo "Make Devel Successful!!"
