### ISSUE TITLE
the wrong  usage in  backup_diag_variant_buffer ？

### ISSUE THREAD

**Issue by 0x0916** [alibaba/diagnose-tools#64]
https://github.com/alibaba/diagnose-tools/blob/master/SOURCE/module/pub/variant_buffer.c#L131
https://github.com/alibaba/diagnose-tools/blob/master/SOURCE/module/pub/variant_buffer.c#L142

I think the memcpy should be the following:
```
memcpy(buffer->product.data + buffer->product.len, .....
```
the current code may cause the data overwritten.

**Comment by git-baoyou** [comment]
在调用backup_diag_variant_buffer和其他API前，都有mutex / spinlock 锁保护，请再确认一下是否有问题

**Comment by wufan618223** [comment]
您好，我觉得不是锁保护的问题。
void backup_diag_variant_buffer(struct diag_variant_buffer *buffer)
{
	unsigned long flags;

	if (!buffer->alloced)
		return;

	diag_variant_buffer_mutex_lock(buffer);
	diag_variant_buffer_spin_lock(buffer, flags);

	buffer->product.len = 0;
	if (buffer->buffer_toggle == 0) {
		if (buffer->buffers[1].pos) { /**如果buffers[1]有数据，则拷贝到buffer->product.data中**
			memcpy(buffer->product.data,
				buffer->buffers[1].data, buffer->buffers[1].pos);
			buffer->product.len = buffer->product.len + buffer->buffers[1].pos;
		}
		if (buffer->buffers[0].pos) {//**如果buffers[0]有数据，则拷贝到buffer->product.data中**
			memcpy(buffer->product.data,
				buffer->buffers[0].data, buffer->buffers[0].pos);
			buffer->product.len = buffer->product.len + buffer->buffers[0].pos;
		}
	} else {
但是两次都是拷贝到buffer->product.data的开始位置，如果buffers[1]和buffers[0]同时有数据，就会存在之前的数据被覆盖的问题。请确认～

**Comment by git-baoyou** [comment]
谢谢，这里确实会丢数据。
