### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by wufan618223** [alibaba/diagnose-tools#67]
在hrtimer_handler函数中：
if (in_irq()) {
		irq_delay_timer(context);
		syscall_timer(context);
		diag_load_timer(context);
		sys_loop_timer(context);
		perf_timer(context);
		utilization_timer(context);
}
我不太理解为什么一定要放在in_irq中呢？

**Comment by git-baoyou** [comment]
因为在函数里面会访问中断上下文的数据，如果在CPU热插拔的时候，相应的定时器回调可能处于进程上下文，此时去访问中断上下文可能触发宕机。

**Comment by wufan618223** [comment]
感谢指教～
